Intervention/image

- src/Intervention/Image/AbstractDecoder.php
- tests/AbstractDecoderTest.php
Simply this, an image init option, implemented in AbstractDecoder, to read an image stream. I've implemented the same kind of tests set for other types of images
> Read stream

- src/Intervention/Image/ImageServiceProviderLumen.php
Removes config_path()/publishes calls
> Add Lumen ServiceProvider

- src/Intervention/Image/ImageServiceProviderLeague.php
This PR adds a service provider that simplifies integrating Intervention within applications using League\Container
> Added a service provider for league\container

- src/Intervention/Image/Gd/Commands/FitCommand.php
- src/Intervention/Image/Gd/Commands/LimitColorsCommand.php
- src/Intervention/Image/Gd/Commands/ResizeCanvasCommand.php
- src/Intervention/Image/Gd/Decoder.php
- src/Intervention/Image/Gd/Driver.php
- src/Intervention/Image/ImageServiceProviderLaravel5.php
- src/Intervention/Image/Imagick/Decoder.php
- src/Intervention/Image/Imagick/Driver.php
- tests/AbstractDecoderTest.php
:exclamation: Blocked by #491.
This PR
> Fix: Remove unused imports

- provides.json
Issue [#573](https://github.com/Intervention/image/issues/573)
Attempt to correct syntax error.
> Updated provides.json Backslash syntax error

- src/Intervention/Image/AbstractDecoder.php
I tried to read image from a S3 Amazon stream, but it failed when trying to call rewind(), because that stream is not seekable.
Fix is inspired by this commit, they had the same issue: https://github.com/thephpleague/flysystem/commit/cbd2d5a9c47496a8c2b64047ec2612c88c894022
> Fixed issue when reading image from stream if stream is not seekable

- src/Intervention/Image/ImageServiceProviderLaravel5.php
Share method will be removed as of Laravel 5.4
https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736#diff-52441e04e14c52275cd5d09e8f958981L300
> Fix undefined method

- src/Intervention/Image/ImageServiceProviderLumen.php
We ran into an issue where the library didn't pick up the changed driver setting on lumen. 
The attached changes resolved that issue.
> Fixed issue with lumen not picking up the app/config/image.php configuration file

- src/Intervention/Image/Imagick/Commands/ExifCommand.php
- tests/ExifCommandTest.php
Sorry @olivervogel, I made a mistake in PR #659. Just one character, but wrong! You would make me very happy to merge this one and the next PR!
> fix exif imagick bug when reading complete array of exif data

- src/Intervention/Image/ImageServiceProviderLumen.php
Update ImageServiceProviderLumen based on 5.4 releases, replacing of share by singleton
> Update ImageServiceProviderLumen 5.4

- src/Intervention/Image/Imagick/Decoder.php
Fix for issue: #607 
IMGTYPE_TRUECOLORMATTE -> IMGTYPE_TRUECOLOR
> handle IM7 constant change

- src/Intervention/Image/Image.php
Ref issue [#584](https://github.com/Intervention/image/issues/584)
> Apply hexdec function to hexadecimal color value

- src/Intervention/Image/Image.php
Fix copy-paste error from #687. Will need tagging again.
> [1.6] Fix parseColor() with 3-char hex codes

- src/Intervention/Image/ImageServiceProvider.php
This is an actual fix for #621
> Don't run service provider boot method if absent

- src/Intervention/Image/AbstractDecoder.php
Follow-up to #718.
I don't feel safe when it can break just by altering the code ordering ^^
> Add a code comment to prevent future regressions

- src/Intervention/Image/AbstractFont.php
- src/Intervention/Image/Imagick/Font.php
In addition to #165 it would be great if `imagick` also supports this method.
> add getBoxSize() for imagick

- src/Intervention/Image/Facades/Image.php
Facilitates autocomplete when using the Facade
> PHPDoc static methods for Facade

- src/Intervention/Image/Imagick/Encoder.php
> Ensure WebP image background is transparent

- src/Intervention/Image/AbstractDecoder.php
- tests/AbstractDecoderTest.php
- tests/GdSystemTest.php
- tests/ImagickSystemTest.php
> Handle whitespaced b64

- src/Intervention/Image/Response.php
This would make response method play nice with Symfony, Silex and any other project that uses Symfony's http stack.
> Add support for Symfony Response creation

- composer.json
- src/Intervention/Image/AbstractDriver.php
Follow-up to #837, see also #882.
> Improving the fix for support of custom commands with accentuated names

- src/Intervention/Image/Gd/Commands/ResetCommand.php
Adds support for PHP8/GDImage to src/Intervention/Image/Gd/Commands/ResetCommand.php
> Add PHP8 GDImage object support

- src/Drivers/Abstract/AbstractImage.php
- src/Drivers/Gd/Encoders/WebpEncoder.php
- src/Drivers/Imagick/Encoders/WebpEncoder.php
- src/Interfaces/ImageInterface.php
- tests/AbstractImageTest.php
- tests/Drivers/Gd/Encoders/WebpEncoderTest.php
- tests/Drivers/Imagick/Encoders/PngEncoderTest.php
- tests/Drivers/Imagick/Encoders/WebpEncoderTest.php
This PR adds:
- Webp encoders for GD & ImageMagick
- PNG encoder test for ImageMagick
> [Next] Webp encoders for GD & ImageMagick

- src/Intervention/Image/Gd/Commands/BrightnessCommand.php
Change implicit float->int conversion with use of round(x,0)
> Remove a php 8.1 deprecation warning

- src/Intervention/Image/Commands/AbstractCommand.php
Unused use statements must be removed.
> No unused imports

- src/Drivers/Imagick/Encoders/HeicEncoder.php
- src/Encoders/FileExtensionEncoder.php
- src/Encoders/HeicEncoder.php
- src/Encoders/MediaTypeEncoder.php
- src/Image.php
- src/Interfaces/ImageInterface.php
- tests/Drivers/Imagick/Encoders/HeicEncoderTest.php
Possibility to Encode & Decode HEIC/HEIF image files. (Imagick only)
> Implement HeicEncoder

- .editorconfig
- .gitattributes
- composer.json
- phpcs.xml
Implemented PSR-12 PHPCS config and added .editorconfig for development standardization
> Added PHPCS config and dependencies

- src/Drivers/Gd/Modifiers/PlaceModifier.php
- src/Drivers/Imagick/Modifiers/PlaceModifier.php
- src/Image.php
- src/Interfaces/ImageInterface.php
- src/Modifiers/PlaceModifier.php
- tests/Drivers/Gd/Modifiers/PlaceModifierTest.php
- tests/Drivers/Imagick/Modifiers/PlaceModifierTest.php
> Add opacity parameter to PlaceModifier

- phpstan.dist.neon
- src/Colors/Cmyk/Color.php
- src/Colors/Hsl/Color.php
- src/Colors/Hsv/Color.php
- src/Colors/Rgb/Color.php
- src/Drivers/Gd/Analyzers/PixelColorAnalyzer.php
- src/Drivers/Gd/Cloner.php
- src/Drivers/Gd/Frame.php
- src/Drivers/Gd/Modifiers/ContainModifier.php
- src/Drivers/Gd/Modifiers/CoverModifier.php
- src/Drivers/Gd/Modifiers/CropModifier.php
- src/Drivers/Gd/Modifiers/ResizeCanvasModifier.php
- src/Drivers/Gd/Modifiers/ResizeModifier.php
- src/Drivers/Gd/Modifiers/RotateModifier.php
- src/Drivers/Imagick/Analyzers/PixelColorAnalyzer.php
- src/Drivers/Imagick/Modifiers/ColorspaceModifier.php
- src/Interfaces/ColorChannelInterface.php
- src/Interfaces/ColorInterface.php
- src/Interfaces/ColorProcessorInterface.php
- src/Interfaces/DriverInterface.php
- src/Modifiers/ColorspaceModifier.php
Last PR on the "exception" track @olivervogel.
NB: `@throws void` is a tips to tell phpstan than even if the method is technically throwing exception, it does throws nothing in this case.
> Add more exception annotation

- composer.json
- src/Drivers/Gd/Encoders/GifEncoder.php
- src/Drivers/Gd/Encoders/JpegEncoder.php
- src/Drivers/Imagick/Encoders/GifEncoder.php
- src/Drivers/Imagick/Encoders/JpegEncoder.php
- src/Encoders/FileExtensionEncoder.php
- src/Encoders/FilePathEncoder.php
- src/Encoders/GifEncoder.php
- src/Encoders/JpegEncoder.php
- src/Encoders/MediaTypeEncoder.php
- src/Image.php
- src/Interfaces/ImageInterface.php
- tests/ImagickTestCase.php
- tests/Traits/CanDetectProgressiveJpeg.php
- tests/Unit/Drivers/Gd/Encoders/GifEncoderTest.php
- tests/Unit/Drivers/Gd/Encoders/JpegEncoderTest.php
- tests/Unit/Drivers/Imagick/Encoders/GifEncoderTest.php
- tests/Unit/Drivers/Imagick/Encoders/JpegEncoderTest.php
- Add progressive Jpeg encoding
- Add interlaced GIF encoding
> Add Encoder Options

- src/Drivers/Imagick/Modifiers/PlaceModifier.php
- tests/Unit/Drivers/Gd/Modifiers/PlaceModifierTest.php
- tests/Unit/Drivers/Imagick/Modifiers/PlaceModifierTest.php
> Fix discarded alpha channel of watermark in PlaceModifier

- src/Drivers/AbstractFontProcessor.php
- src/Drivers/Gd/FontProcessor.php
- tests/Unit/Drivers/AbstractFontProcessorTest.php
> Fix bug when centering non-latin characters

- src/Drivers/Imagick/Modifiers/ResizeCanvasModifier.php
- tests/Unit/Drivers/Imagick/Modifiers/ResizeCanvasModifierTest.php
> Fix bug with overlapping colors in ResizeCanvasModifier

- src/Drivers/Gd/Analyzers/PixelColorAnalyzer.php
- src/Drivers/Gd/ColorProcessor.php
- tests/Unit/Drivers/Gd/ColorProcessorTest.php
- tests/Unit/Drivers/Gd/Modifiers/QuantizeColorsModifierTest.php
- tests/Unit/Drivers/Imagick/Modifiers/QuantizeColorsModifierTest.php
Resolves https://github.com/Intervention/image/issues/1409
> Fix incorrect color results after color reduction
