src/Intervention/Image/Commands/IptcCommand.php

When getting the iptc data from an image, only one "Keyword" is returned. This PR allows multiple keywords to be returned in an array.

Return array of iptc keywords instead of just the first

---

src/Intervention/Image/Imagick/Commands/FitCommand.php
tests/FitCommandTest.php

Same fix as in #353, Fit command used resize with FILTER_BOX filter instead of scale.

Change Imagick method for fitCommand

---

src/Intervention/Image/AbstractDecoder.php
tests/FillCommandTest.php

As described in the [Color Format documentation](http://image.intervention.io/getting_started/formats) the Image::fill() accept array data for RGB and RGBA implementation. 
In fact, when using this causes Warning errors, It's ok that is not accepted as [Fill documentation](http://image.intervention.io/api/fill), but I guess now it works.
**RGB** *array(50, 50, 50)*
> preg_match() expects parameter 2 to be string, array given
>  /var/www/html/git/image/src/Intervention/Image/AbstractDecoder.php:242
>  /var/www/html/git/image/src/Intervention/Image/AbstractDecoder.php:207
>  /var/www/html/git/image/src/Intervention/Image/AbstractDecoder.php:287
>  /var/www/html/git/image/src/Intervention/Image/Gd/Commands/FillCommand.php:30
>  /var/www/html/git/image/tests/FillCommandTest.php:33
**RGBA** …

Added support for Image::fill() with array (RGB / RGBA)

---

src/Intervention/Image/Image.php
tests/ImageTest.php

`isEncoded()` always returns true, even if no encoded image exists.
The `encoded` property of `Intervention\Image\Image` is initialised as an empty string:
```
/**
* Last image encoding result
*
* @var string
*/
public $encoded = '';
```
But `isEncoded()` checks if it is null:
```
/**
* Checks if current image is already encoded
*
* @return boolean
*/
public function isEncoded()
{
return ! is_null($this->encoded);
}
```
Change the function to check for an empty string instead. Added unit test coverage.

Fix isEncoded() Return Value

---

src/Intervention/Image/ImageServiceProviderLaravel5.php

A specific, well-known javascript library requires retina images to be postfixed by '@2x'.
Intervention-image doesn't allow for '@' as a possible character in the filename, making both unusable together.
Currently, I've made the change in forks of your project which I use as repositories, but if you think the change might be useful, here it is.

added support for @ in filename

---

src/Intervention/Image/AbstractEncoder.php

At an .ico image I got the type "image/x-ico" and not image/x-icon
```
PHP Fatal error:  Uncaught exception 'Intervention\Image\Exception\NotSupportedException' with message 'Encoding format (image/x-ico) is not supported.' in /packages/intervention/image/src/Intervention/Image/AbstractEncoder.php:149
```

Encoding format (image/x-ico) is not supported.

---

.travis.yml

This PR
:information_desk_person: Apparently the builds currently fail because installing the extension does not automatically enable it on PHP5.4.
For reference, see 
* https://docs.travis-ci.com/user/languages/php/#Preinstalled-PHP-extensions
* http://stackoverflow.com/a/28686068/1172545

Fix: Enable imagick extension on PHP5.4

---

src/Intervention/Image/Imagick/Driver.php
tests/AbstractDecoderTest.php

:exclamation: Blocked by #491.
This PR

Fix: Case-insensitive method calls and class names

---

src/Intervention/Image/Imagick/Decoder.php

Hi!  :v: Throwing an Exception from a `catch` block hides the original exception message. Sometimes Imagick exceptions contain useful information, like if your installation isn't compiled with PNG support. Changing this to point to the original exception using PHP's Exception chaining could make such problems more clear.
This is the only place where a different exception is thrown from a `catch` block, so I didn't touch anything else :)

Chain Imagick exceptions instead of hiding

---

src/Intervention/Image/ImageServiceProvider.php

When using get_class, in Lumen the $this->app could only be an instance of the \Laravel\Lumen\Application and not an instance of a class extending from \Laravel\Lumen\Application. When using the instanceof check people can use a custom application class extending from the main Lumen Application class. To make this work i had to remove the use statements at the top and replace the references in getProvider with the full paths.

replace get_class with instanceof for $this->app

---

src/Intervention/Image/Gd/Driver.php
src/Intervention/Image/Imagick/Driver.php

Helpful when using a custom driver which extends a base driver.

Use static in drivers newImage()

---

src/Intervention/Image/Response.php

Using the full name avoids problems where the user has commented out the Laravel aliases or has aliased "Response" to something else.
I, for one, don't use Laravel's aliases and have commented them out. But this library currently expects the alias to be there.

Use \Illuminate\Support\Facades\Response instead of the \Response alias

---

src/Intervention/Image/Imagick/Commands/ExifCommand.php
tests/ExifCommandTest.php
tests/ImagickSystemTest.php

This PR adds support for `$image->exif()` when using `Imagick`, without  requiring exif extension. It uses the methods [`getImageProperty`](http://php.net/manual/en/imagick.getimageproperty.php) and [`getImageProperties`](http://php.net/manual/en/imagick.getimageproperties.php) when they are available. If the extension is available, however, it prefers the extension over the imagick methods.

add support for exif to imagick extension 

---

src/Intervention/Image/AbstractFont.php

This allows a nicer experience when manipulating the font.
Before:
```php
function(AbstractFont $font) {
$font->font('font.otf');
$font->size(16);
$font->color('#fff');
}
```
After:
```php
function(AbstractFont $font) {
$font->font('font.otf')
->size(16)
->color('#fff');
}
```

Make AbstractFont a fluent interface

---

src/Intervention/Image/AbstractDecoder.php

Several image providers have detection for which user agent is being used. 
Since I had several times issue's with that images where unavailable for Intervention since an missing user agent, I decided to add this header to get rid of the problems.

Update URL function, with browser headers

---

src/Intervention/Image/AbstractDecoder.php

Several image servers have detection for which user agent is being used. 
Since I had several times issue's with that images where unavailable for Intervention since an missing user agent, I decided to add this header to get rid of the problems.

Add user agent header initFromUrl

---

src/Intervention/Image/ImageManager.php
tests/ImageManagerTest.php

I want to extend some of the drivers. More specifically, since exif extension does not have support for streams, I must use the Imagick driver. However, in PR #659 I choose to prefer the exif extension over Imagick to prevent any possible BC break.
So I want to implement my own driver that just extends the Imagick driver a little bit. Currently, that is not possible. With this PR, you can also pass an object to the `driver` key in the `config` array.

allow intervention to use own drivers

---

src/Intervention/Image/Exception/ImageException.php
src/Intervention/Image/Exception/InvalidArgumentException.php
src/Intervention/Image/Exception/MissingDependencyException.php
src/Intervention/Image/Exception/NotReadableException.php
src/Intervention/Image/Exception/NotSupportedException.php
src/Intervention/Image/Exception/NotWritableException.php
src/Intervention/Image/Exception/RuntimeException.php

Base `Exception` class allows to catch all exceptions belonging to `Intervention\Image` without unrelated `\RuntimeException`s.
Naming and namespace are a proposition.

Introduce base ImageException class

---

src/Intervention/Image/AbstractDecoder.php

exchange positiion checking isFilePath and isBase64 and catch the error while checking is_file

[FIX] File name is longer than the maximum allowed path length in some OS

---

.travis.yml

Currently the Travis config runs the latest stable version of PHPUnit which is incomparable with PHP 5, causing tests to fail unnecessarily. I have made a small amend to the config so that the PHPUnit version used is the one specified in composer.json, meaning the tests pass from PHP 5.4 - PHP 7.1

Update Travis CI config to allow pass for PHP 5.4 - 5.6

---

src/Intervention/Image/AbstractDecoder.php

Since 2.3.12, a bug seems to have been introduced to `AbstractDecoder.php` that prevents loading images from file paths. I believe it was introduced [in this commit](https://github.com/Intervention/image/commit/58881f0bc8d32c25aff5d97a6433bc067a128fdb).
If I pass in a valid file path, such as `/tmp/MyImageFile`, line 332 of `AbstractDecoder.php` interprets it as base-64 text, and subsequently tries to decode an image from the file path string:
```
case $this->isBase64():
return $this->initFromBinary(base64_decode($this->data));
case $this->isFilePath():
return $this->initFromPath($this->data);
```
I think the `$this->isFilePath()` evaluation should come *before* the `$this->isBase64()` evaluation - as a file path string will always evaluate to Base 64.

Bugfix: File path strings are always evaluated as Base64-data

---

src/Intervention/Image/Gd/Decoder.php

For some image the function 'imagecreatefromstring' does'nt work beacause the image is in violation with the jpeg spec. 
https://stackoverflow.com/questions/35337709/invalid-sos-parameters-for-sequential-jpeg/43271528#43271528

Use imagecreatefromstring when imagecreatefromjpeg fail

---

src/Intervention/Image/AbstractDecoder.php
tests/AbstractDecoderTest.php

Fixes #747 
This PR allows image objects to be initialised from PSR `StreamInterface`s. Doing so allows for a more fluid API as the types returned by `$image->stream()` will be accepted in `Image::make($stream)` too.

NEW Allow images to be initiated from PSR StreamInterfaces

---

.travis.yml
composer.json

These changes get travis working on my fork.
~~There's a test failure, but that's out of scope for a PR just intended to get the tests running.~~
`sudo: false` - to get us on the new infrastructure
Removed apt-get installs (can't do that on `sudo: false` and they failed anyway - I'm not sure if they are really needed?
Install imagick with pecl
`composer self-update || true` stops the build failing if we can't update composer for whatever reason
`composer install`:
- `--prefer-dist` it's faster than from source
- `--no-progress` we don't need progress for our builds so lets turn it off for more succinct output 
- `--no-suggest` as above, we don't need this output for builds
- `--optimize-autoloader` to hopefully speed up builds by making the autoloader a bit faster

Get travis working

---

src/Intervention/Image/ImageServiceProviderLaravel5.php

Discovered a bug where filenames with parenthesis are not supported.
E.g. example(1).jpg
I think there are probably other valid filename characters that aren't supported - I've not put in any more research. 
This pull request fixes the issue for parenthesis.

Allow parenthesis in Laravel5 filename when using imagecache

---

src/Intervention/Image/Gd/Commands/BackupCommand.php
src/Intervention/Image/Gd/Driver.php
src/Intervention/Image/Imagick/Commands/BackupCommand.php
tests/BackupCommandTest.php

I've been having an issue with PNGs rendering with black backgrounds and narrowed it down to an issue when cloning the image resource.
```php
$manager = new ImageManager();
$image = $manager->make('/path/to/image.png');
$newImage = clone $image;
$newImage->resize($width, $height);
$newImage->save('/path/to/newimage.png');
```
In this example newimage.png would be replacing all transparent pixels with black pixels.
This is because the new canvas which is created when `Gd\Driver::cloneCore` is called doesn't set the cloned image's background to transparent and so it stays at the default (black).
This fix makes sure that all changes are applied onto a transparent background when cloning images.

FIX PNGs are now transparent when created from clones

---

src/Intervention/Image/Gd/Commands/RotateCommand.php
src/Intervention/Image/Imagick/Commands/RotateCommand.php
tests/RotateCommandTest.php

Applying a rotation value more than this may use unnecessary server side resources. For example, rotating an image by 9999999999 degrees causes the PHP process to continue indefinitely for me.

Restrict the maximum rotation value to 360 degrees

---

src/Intervention/Image/Imagick/Decoder.php

Like in issue #580 for read from file - setting the background to transparent is needed when reading SVG from Blob to avoid a white backround

Transparent Background for Images read from Blob

---

src/Intervention/Image/ImageServiceProviderLaravel5.php

This is useful when you want to override this method, for example when used with imagecache to set it to look for images in AWS S3 as well.

- make private method protected

---

src/Intervention/Image/Commands/ExifCommand.php

PNGs sometimes don't have exif data, and corrupted images might have corrupted versions. This function raises exceptions in these cases are not handled. 
This PR changes that to throw a relevant exception, to be handled upstream. 
Related:
https://github.com/Intervention/image/issues/917

2.4.2 Fix exif errors on PNG / corrupted images

---

src/Intervention/Image/Size.php

Avoid 0px result dimensions when resizing images with extreme ratios

---

src/Intervention/Image/Imagick/Font.php

I had the same issue as described here: #498
The attached changes resolved it.
More details:
When using "$font->valign('top');" position of wrapped text (>1 lines) is broken. It is well described in the issue itself.
Solution is connected only with Imagick driver and it is about counting $dimentions connected with one line only by setting multiline param as false.
http://php.net/manual/en/imagick.queryfontmetrics.php

498_fix_text_top_vertical_position_multiline_imagick

---

src/Intervention/Image/Image.php
tests/ImageTest.php

Hello.
I have a problem to save the image in the format I need I have to add EXT to it and then move it.
```php
$filepath = $path . '.jpg';
$image->save($filepath);
copy($filepath, $path);
unlink($filepath);
```
This PR fix this issue.

added the $format parameter to the save method

---

src/Intervention/Image/Gd/Font.php

In some server configration, Multibyte text is not rendered ( is not encoded properly).
PDF Library DOMPDF  is doing like this way.
`$text = mb_encode_numericentity($text, array(0x0080, 0xffff, 0, 0xffff), 'UTF-8'); `
https://github.com/dompdf/dompdf/blob/313f466e77fe63df0c53c20b54540945a0b165cd/src/Adapter/GD.php#L866
This is error log.
```
imagettfbbox(): any2eucjp(): invalid code in input string {"exception":"[object] (ErrorException(code: 0): imagettfbbox(): any2eucjp(): invalid code in input string at /usr/home/webapp/vendor/intervention/image/src/Intervention/Image/Gd/Font.php:85)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'imagettfbbox():...', '/usr/home/...', 85, Array)
#1 …
```

Multibyte text is not rendered

---

src/Intervention/Image/AbstractDecoder.php

In [PHP 8.0, `gd` resources are changed to `\GdImage` class objects](https://php.watch/versions/8.0/gdimage). This changes the `\Intervention\Image\AbstractDecoder::isGdResource` method to accept `\GdImage` objects as well as `gd` resources.

PHP 8: Add support for GdImage resource objects

---

src/Intervention/Image/AbstractFont.php

Fixes an incorrect docblock. Sadly triggered PHPstan:
```Parameter #1 $text of class Intervention\Image\Gd\Font constructor expects Intervention\Image\Strinf|null, string given. ```

Fix incorrect docblock in AbstractFont (Strinf -> String)

---

src/Intervention/Image/AbstractDecoder.php

my company uses this package for fasting image processing, but when we deploy to k8s with istio, the envoy sidecar requires newer HTTP version, so i think we should improve http context from HTTP 1.0 (default to HTTP Context) to HTTP 1.1 with context options 'http.protocol_version'.

Fix Decoder::initFromUrl under service mesh with envoy side raise a 426 http code

---

src/Intervention/Image/Gd/Commands/RotateCommand.php
src/Intervention/Image/Imagick/Commands/RotateCommand.php

Hi, this is my first pull request on GitHub. I hope I don't mess anything up.
It turns out that the restriction on rotations beyond 360 degrees prevents decimal accuracy. Using fmod instead of the % operator preserves the constraint and allows the use of angles with decimals.

Allow rotation angle with decimals

---

src/Intervention/Image/AbstractEncoder.php
src/Intervention/Image/Gd/Encoder.php
src/Intervention/Image/Imagick/Encoder.php
tests/EncoderTest.php

This PR adds support for the AVIF encoding.
The AVIF format has been supported in ImageMagick since [at least 7.0.10-21](https://github.com/ImageMagick/ImageMagick/commit/9f4c23df9e6a462dcef91f98aecce64d78552a5d). I personally have tested it on 7.0.10-25 along with [this](https://github.com/ImageMagick/ImageMagick/issues/1432#issuecomment-671036653) person.
This closes #891

AVIF Support

---

src/Intervention/Image/AbstractEncoder.php

Sometimes JPEG images carry the image/jp2 MIME type (JPEG2000 encoding). ImageMagick supports this if it has the correct delegates compiled.

Support JP2 images

---

src/Intervention/Image/AbstractDecoder.php

Remove the newlines before doing a Regex check inside the `decodeDataUrl` method in the same way that is the `isBase64` method doing.
Some base64 encoded images contains newlines, passing them directly to the `Image::make` method can result in a `NotReadableException`.
Here are the tests I did before this commit :
- data part only  =>  OK 
- data:[..] header  +  data part  =>  OK
- data part only with newlines  =>  OK
- data:[..] header  +  data part with newlines  =>  Failure

Bugfix for decodeDataUrl when data contains newlines

---

src/Intervention/Image/AbstractFont.php
src/Intervention/Image/Gd/Font.php
src/Intervention/Image/Imagick/Font.php
tests/AbstractFontTest.php

This is sort of in reference to issue #619.
It doesn't appear that GD supports this sort of simple implementation out of the box, although it could be done with a more complicated algorithm if needed.

Add support for text kerning (ImageMagick only)

---

src/Intervention/Image/ImageServiceProviderLaravelRecent.php

Updated filename regex pattern to allow the equal sign as being part of the filename portion of the route, otherwise it would fall on 404 error.

Add support to equal sign - '=' - on URL

---

src/Intervention/Image/Size.php

The <code>insert</code> command ignore specified <code>offset</code> if position == **center**.
An example:
```php
$canvas = Image::canvas(600, 600, '#ff0000');
$canvas1 = Image::canvas(400, 400, '#f6ff00');
$canvas->insert($canvas1, 'center', 150, 150);
return $canvas->response();
```
Wrong:
Fixed:

Fix “insert” offset with center position

---

src/Intervention/Image/AbstractFont.php

This simply corrects the return type for the methods in AbstractFont.php that return `$this`
This fixes warnings similar to this in code editors that use IntelliSense

Use correct docbock returns in AbstractFont.php

---

src/Intervention/Image/Gd/Encoder.php
tests/EncoderTest.php

This PR adds support for the AVIF imagetype in the GD driver.
GD AVIF support will be available in PHP 8.1: https://github.com/php/php-src/pull/7026
I've tested this on PHP 8.1beta3

GD AVIF support

---

src/Collection.php
src/Drivers/Gd/Modifiers/BrightnessModifier.php

Fixed a couple of warnings with PHP 8.1:
```
PHP Deprecated:  Implicit conversion from float 76.5 to int loses precision in /Users/deluxetom/Dev/dlxmedia/intervention-image/src/Drivers/Gd/Modifiers/BrightnessModifier.php on line 18
```
```
PHP Deprecated:  Return type of Intervention\Image\Collection::getIterator(): iterable should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/deluxetom/Dev/dlxmedia/intervention-image/src/Collection.php on line 36
```

Fixed deprecation warnings with PHP 8.1

---

README.md

Fix the hyperlinks by updating the URL that they are pointing to on the intervention.io website.

Update broken README documentation hyperlinks

---

src/Intervention/Image/AbstractDecoder.php

Some services, like https://lucid.app/documents/image/882959d4-782d-44f7-8e13-ca4f338e0876/2/2000 recognizes Intervention/image user agent as an old browser and serve redirect, instead of image content. This PR updates `user-agent` to latest stable chrome version.
Before:
```
curl -H "User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2" https://lucid.app/documents/image/882959d4-782d-44f7-8e13-ca4f338e0876/2/2000 -I
HTTP/1.1 302 Found
content-length: 0
location: https://www.lucidchart.com/pages/old_browser
[...]
```
After:
```
curl -H "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36" https://lucid.app/documents/image/882959d4-782d-44f7-8e13-ca4f338e0876/2/2000 -I
HTTP/1.1 200 …
```

Update User-Agent to latest Chrome

---

src/Intervention/Image/Gd/Commands/ResizeCommand.php

This is intended to stop deprecation notices on PHP 8.1, e.g.:
```
Implicit conversion from float 256.8493150684931 to int loses precision in /.../vendor/intervention/image/src/Intervention/Image/Gd/Commands/ResizeCommand.php on line 67 [] []
```
The other usages of these functions don't look like they will cause this problem.

Explicitly convert to integer

---

src/Intervention/Image/Gd/Color.php
src/Intervention/Image/Imagick/Color.php

Use && and || logical operators instead of and and or.

Logical operators

---

src/Image.php

`image.php` implemented two interface, `ImageInterface` and  `Countable`.
but `ImageInterface` interface already included `Countable`, So, this one is extra and can be deleted.

duplicate Countable Interface in image.php

---

src/Drivers/Gd/Decoders/FilePathImageDecoder.php
src/Drivers/Imagick/Decoders/FilePathImageDecoder.php

PHP enconters problems on some machines when `is_file()` in the FilePathImageDecoders receive values that are longer than the maximum-path-length of the host.
This fix checks if the input is in this maximum path length.
See #708

Fix bug with very long file/path names

---

src/Drivers/Imagick/Decoders/BinaryImageDecoder.php

Fixes: https://github.com/Intervention/image/issues/1261

Fix decoding error with Imagick driver

---

src/Collection.php
src/Drivers/Gd/Modifiers/SliceAnimationModifier.php
src/Drivers/Imagick/Core.php
src/Drivers/Imagick/Modifiers/SliceAnimationModifier.php
src/Image.php
src/Interfaces/CollectionInterface.php
src/Interfaces/CoreInterface.php
src/Interfaces/ImageInterface.php
src/Modifiers/SliceAnimationModifier.php
tests/CollectionTest.php
tests/Drivers/Imagick/CoreTest.php

> public Image::sliceAnimation(int $offset, null|int $length = null): ImageInterface
Extract animation frames based on given values and discard the rest. The offset
parameter can be used to set the starting point of the new animation; all
frames before the offset are discarded. The length parameter is optional. It
specifies how many frames to read after the offset. By default, all frames up
to the end of the animation are read.
| Name | Type | Description |
| - | - | - |
| offset | integer | Starting point of the new animation |
| length | null or integer | Frames to read after the offset (optional) |
```php
use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Gd\Driver;
// create new manager instance with desired driver
$manager = new ImageManager(new Driver());
// reading …
```

Implement Image::sliceAnimation()

---

src/Interfaces/ImageInterface.php

ImageInterface encode argument is not aligned with Image class.
**ImageInterface.php**
`public function encode(EncoderInterface $encoder): EncodedImageInterface;`
**Image.php**
`public function encode(EncoderInterface $encoder = new AutoEncoder()): EncodedImageInterface`
This is causing static analysis tools to fail as well as confuse IDEs with error:
`Method Intervention\Image\Interfaces\ImageInterface::encode() invoked with 0 parameters, 1 required.`

Fix ImageInterface encode() method argument

---

src/Geometry/Rectangle.php

`DrawableInterface` is already implemented by Polygon and it is not needed on Rectangle. *Just found this little detail while checking the methods for the documentation update.*

Remove redundant DrawableInterface for Rectangle class

---

src/Drivers/Gd/Decoders/AbstractDecoder.php

Hi @olivervogel 
I'm getting some 
```
Warning: getimagesize(): PNG file corrupted by ASCII conversion
```
from this code.
Since, a `!in_array` check is thrown with an exception. The warning should be muted.

Avoid warning on getimage call

---

src/Decoders/NativeObjectDecoder.php
src/Drivers/Gd/Decoders/BinaryImageDecoder.php
src/Drivers/Gd/Decoders/FilePathImageDecoder.php
src/Drivers/Gd/Decoders/NativeObjectDecoder.php
src/Drivers/Gd/InputHandler.php
src/Drivers/Imagick/Decoders/BinaryImageDecoder.php
src/Drivers/Imagick/Decoders/FilePathImageDecoder.php
src/Drivers/Imagick/Decoders/NativeObjectDecoder.php
src/Drivers/Imagick/InputHandler.php
tests/Unit/Drivers/Gd/InputHandlerTest.php
tests/Unit/Drivers/Imagick/InputHandlerTest.php

```php
use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Gd\Driver;
// create image manager with desired driver
$manager = new ImageManager(new Driver());
// read GDImage
$image = $manager->read(imagecreatetruecolor(300, 200));
```

Add ability to read Imagick or GDImage directly with ImageManager

---

src/Format.php
tests/Unit/Encoders/FileExtensionEncoderTest.php
tests/Unit/Encoders/MediaTypeEncoderTest.php

This deals with the problem that arises when format-unspecific encoders are provided with parameters that are not present in the final target encoder.
For example, the following call can take place with the `quality` argument.
```php
// works if $image was created from jpeg, errors if image source is png for example
$encoded = $image->encode(new AutoEncoder(quality: 5));
```
If the source image and thus the target encoder supports `quality` (e.g. Jpeg), everything works fine. However, if the input format does not contain `quality` in the target encoder (e.g. PNG), an error occurs.
> Unknown named parameter $quality  
The logic has only been adapted since version 3.6, so this does not affect previous versions.
See #1332

Bugfix: Filter out parameter that do not match target encoder

---

src/ImageManager.php
src/Interfaces/ImageManagerInterface.php

In v3 the ImageManager class is now final making it impossible to mock out in tests, and while most other classes in this library have corresponding interfaces enabling mocking this class does not.
This PR adds a new ImageManagerInterface interface with the 4 public instance methods from ImageManager. I've based it off how the Image & ImageInterface pair is set up, so the docblock contents for those methods have also been moved to the interface.
Addresses #1324.

Add ImageManager interface

---

.github/workflows/run-tests.yml
src/Drivers/Imagick/Modifiers/DrawLineModifier.php
tests/Unit/Drivers/Gd/Modifiers/DrawLineModifierTest.php
tests/Unit/Drivers/Imagick/Modifiers/DrawLineModifierTest.php

Fix bug with unwanted color in DrawLineModifer

---

src/Drivers/Gd/Decoders/FilePathImageDecoder.php
src/Interfaces/DriverInterface.php
src/Interfaces/ImageManagerInterface.php

Hi @olivervogel, 
I'm getting multiple warnings:
```
Warning: imagecreatefromjpeg(): gd-jpeg error: cannot allocate gdImage struct
```
or similar message when decoding bad inputs.
Since parent::decode call is already throwing an exception
```
throw new DecoderException('Unable to decode input')
```
there is no need to keep such warning which cannot be easily silenced.

Silence php warning when throwing decoder exceptions

---

src/Interfaces/ImageManagerInterface.php

The [example](https://image.intervention.io/v3/basics/instantiation#examples) uses an array of strings.
It seems to be fine either way when you look at it.
https://github.com/Intervention/image/blob/267d588eb100d5cf36c91fffa3642087aa4c1028/src/Drivers/AbstractDriver.php#L69-L79

Update doctype ImageManagerInterface

---

src/Drivers/AbstractDriver.php
src/Drivers/Gd/Driver.php
src/Drivers/Gd/Modifiers/CoverDownModifier.php
src/Drivers/Imagick/Driver.php
src/Drivers/Imagick/Modifiers/CoverDownModifier.php
src/Modifiers/CoverModifier.php
tests/Unit/Drivers/Gd/Modifiers/CoverDownModifierTest.php
tests/Unit/Drivers/Imagick/Modifiers/CoverDownModifierTest.php
tests/Unit/Drivers/Imagick/Modifiers/CoverModifierTest.php

See: https://github.com/Intervention/image/issues/1359

Fix bug in cover modifiers

---

src/Drivers/Gd/Modifiers/DrawBezierModifier.php
src/Drivers/Imagick/Modifiers/DrawBezierModifier.php
src/Geometry/Bezier.php
src/Geometry/Factories/BezierFactory.php
src/Image.php
src/Interfaces/ImageInterface.php
src/Modifiers/DrawBezierModifier.php
tests/Unit/Drivers/Gd/Modifiers/DrawBezierModifierTest.php
tests/Unit/Drivers/Imagick/Modifiers/DrawBezierModifierTest.php
tests/Unit/Geometry/BezierTest.php
tests/Unit/Geometry/Factories/BezierFactoryTest.php

This commit adds a new bezier curve drawing tool as discussed in #1335.
The following code can be used to generate the sample image below:
```php
require('./vendor/autoload.php');
use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Gd\Driver;
use Intervention\Image\Geometry\Factories\BezierFactory;
// create image manager with desired driver
$manager = new ImageManager(new Driver());
// read image from file system
// to display the sample set correctly the recommended image dimensions should be 350 x 500 pixels
$image = $manager->read('test.png');
// resize image proportionally to 500px height
$image->scale(height: 500);
// fill canvas background
$image = $image->fill('#444');
// draw a red cubic bezier curve
$image->drawBezier(function (BezierFactory $bezier) { …
```

Add bezier curve drawing tool

---

src/Drivers/Gd/Decoders/BinaryImageDecoder.php
src/Drivers/Gd/Decoders/FilePathImageDecoder.php
src/Drivers/Imagick/Decoders/BinaryImageDecoder.php
src/Drivers/Imagick/Decoders/FilePathImageDecoder.php

EXIF data extraction makes only sense for JPEG and TIFF format. This patch checks the format and calls exif_read_data only for appropriate formats.
Previously, the function was also called with formats that can not contain EXIF data. This resulted in warnings.
See #1370

Avoid unnecessary exif_read_data calls

---

src/MediaType.php
tests/Unit/FormatTest.php
tests/Unit/MediaTypeTest.php

I stumbled upon this issue for the second time recently, so I decided to try to submit a PR: I sometimes have to deal with image/x-jpeg files (seems that it's a non-standard mime type, but some use it...).
Without this PR, the code breaks with
`"image/x-jpeg" is not a valid backing value for enum Intervention\Image\MediaType`

Handle non-standard but still in use image/x-jpeg mimetype as JPEG

---

src/Drivers/Imagick/Encoders/WebpEncoder.php

The current logic merges all the layers when using WEBP and Imagick. In an animated image, these layers are the separate frames. Not merging the layers when we're dealing with an animation allows for the creation of animated webp files.
Note: this still does only work with Imagick, GD has no animated webp support yet.

Allow animated WEBP's

---

src/Colors/Cmyk/Color.php
src/Colors/Hsl/Color.php
src/Colors/Hsv/Color.php
src/Colors/Rgb/Color.php
src/Interfaces/ColorInterface.php
tests/Unit/Colors/Cmyk/ColorTest.php
tests/Unit/Colors/Hsl/ColorTest.php
tests/Unit/Colors/Hsv/ColorTest.php
tests/Unit/Colors/Rgb/ColorTest.php

```php
/**
* Determine whether the current color is completely transparent
*
* @return bool
*/
public function isClear(): bool;
```

Implement new method ColorInterface::isClear()

---

src/Drivers/Gd/Encoders/PngEncoder.php
src/Drivers/Imagick/Encoders/PngEncoder.php
src/Encoders/PngEncoder.php
src/Interfaces/ImageInterface.php
tests/BaseTestCase.php
tests/GdTestCase.php
tests/ImagickTestCase.php
tests/Traits/CanInspectPngFormat.php
tests/Unit/Drivers/Gd/Encoders/PngEncoderTest.php
tests/Unit/Drivers/Imagick/Encoders/PngEncoderTest.php

```php
$encoded = $image->toPng(indexed: true);
```

Add option to encode indexed color palette PNG format

---

composer.json

Allow PHPUnit 11

---

src/Colors/AbstractColor.php
src/Drivers/AbstractFrame.php
src/Drivers/Gd/Frame.php
src/Drivers/Imagick/Frame.php
src/EncodedImage.php
src/Geometry/Rectangle.php
src/Image.php
tests/Unit/Colors/Cmyk/ColorTest.php
tests/Unit/Colors/Hsl/ColorTest.php
tests/Unit/Colors/Hsv/ColorTest.php
tests/Unit/Colors/Rgb/ColorTest.php
tests/Unit/Drivers/Gd/FrameTest.php
tests/Unit/Drivers/Gd/ImageTest.php
tests/Unit/Drivers/Imagick/ImageTest.php
tests/Unit/EncodedImageTest.php
tests/Unit/Geometry/RectangleTest.php

Implement __debugInfo() on the following classes:
- `Intervention\Image\Image`
- `Intervention\Image\EncodedImage`
- `Intervention\Image\Drivers\Gd\Frame`
- `Intervention\Image\Drivers\Imagick\Frame`
- `Intervention\Image\Geometry\Rectangle`
- `Intervention\Image\Colors\Rgb\Color`
- `Intervention\Image\Colors\Cmyk\Color`
- `Intervention\Image\Colors\Hsl\Color`
- `Intervention\Image\Colors\Hsv\Color`
The result is more informative debug information when objects of the classes are output via `var_dump()`.
For example the following code:
```php
$color = ImageManager::gd()
->read($path)
->pickColor(0, 0);
var_dump($color);
```
results in:
```
object(Intervention\Image\Colors\Rgb\Color)#9 (4) {
["red"]=>
int(104)
["green"]=>
int(128)
["blue"]=>
int(132)
["alpha"]=>
int(255)
}
```

Implement __debugInfo()

---

src/Drivers/AbstractDecoder.php

This reduces memory usage and speeds up the detection.

GIF detection: Only check the first 6 bytes of the input

---

src/Drivers/AbstractDecoder.php

Removed unnecessary `bin2hex()` conversion.
Follow-up to ac9734129478be387c1914f1c2856d623341128c and #1441.

Simplify GIF magic number detection
